services:
  producao-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - production-order

networks:
  production-order:
    external: true
