apiVersion: v1
kind: Service
metadata:
  name: production-service
spec:
  selector:
    app: fast-food-production
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 32003
  type: NodePort